validation:
  article:
    country:
      codes: "ar, au, at, be, br, bg, ca, cn, co, cz, eg, fr, de, gr, hk, hu, in, id, ie, il, it, jp, lv, lt, my, mx, ma, nl, nz, ng, no, ph, pl, pt, ro, sa, rs, sg, sk, si, za, kr, se, ch, tw, th, tr, ae, ua, gb, us, ve"
      error-message: "Invalid country code"
  comment:
    sort-order:
      values: "asc, desc"
      error-message: "Invalid sort order. Must be 'asc', 'desc', or null"